# Generated by Django 5.2.7 on 2025-10-20 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inx', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Portfolio',
        ),
    ]
